# Generated by Django 5.0.1 on 2024-02-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Register1',
        ),
    ]
