# Generated by Django 5.0.1 on 2024-02-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0002_rename_register_register1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('password', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Register1',
        ),
    ]
