# Generated by Django 4.1.2 on 2022-10-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmodel',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lmodel',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Todo Title'),
        ),
    ]
