# Generated by Django 4.1.2 on 2022-10-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0002_alter_lmodel_description_alter_lmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
