# Generated by Django 4.1.2 on 2022-10-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0003_alter_lmodel_description_alter_lmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
