# Generated by Django 4.1.2 on 2022-10-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
